### ISSUE TITLE
Bug: Infected counter became -2

### ISSUE THREAD

**Issue by mlvnbrj** [anuraghazra/covid19-sim#2]
Based on my observation, the 2 infected are going to the hospital and they've been infected for several times (an infinite loop) until they died.

Maybe it triggers because the dead body is still inside the hospital, dead bodies can still infect. The hospital counter are also flickering, changing 0 to 1

![image](https://user-images.githubusercontent.com/20541950/77597082-b5f7f780-6f38-11ea-8b15-ee33060e51c7.png)

**Comment by anuraghazra** [comment]
Thanks for opening this issue.. yes looks like that's what happening.. or it might also be possible that the ids of the boids are not invalidating that's why the counter is glitching, i'm using ids to count how many boids are infected, dead & alive
